import { createHash } from 'node:crypto'
import { readFileSync, readdirSync } from 'node:fs'
import path from 'node:path'

import withSerwistInit from '@serwist/next'
import type { NextConfig } from 'next'

interface PrecacheEntry {
  url: string
  revision: string
}

/**
 * Page URLs to precache, generated by `scripts/precache-routes.ts` before the
 * build. Serwist's own manifest covers webpack assets only, so without these the
 * app would work offline except for every song in it.
 */
function pageEntries(): PrecacheEntry[] {
  let routes: string[]
  try {
    const file = path.join(process.cwd(), 'generated', 'precache-routes.json')
    routes = JSON.parse(readFileSync(file, 'utf8'))
  } catch (error) {
    console.warn(`[precache] could not read the route list, pages will NOT be precached: ${error}`)
    return []
  }

  // One revision for the whole set: any content change means a new build, and
  // every page is regenerated together anyway.
  const revision = process.env.VERCEL_GIT_COMMIT_SHA ?? String(routes.length)
  return routes.map((url) => ({ url, revision }))
}

/**
 * Files in `public/`, hashed.
 *
 * @serwist/next scans the public folder itself, but *only* when
 * additionalPrecacheEntries is absent — and an empty array is enough to skip it.
 * Since we always pass entries, the scan has to happen here or the icons quietly
 * stop being precached.
 */
function publicEntries(): PrecacheEntry[] {
  const publicDir = path.join(process.cwd(), 'public')

  try {
    return readdirSync(publicDir, { withFileTypes: true })
      .filter((entry) => entry.isFile() && !/^sw\.js(\.map)?$|^swe-worker-/.test(entry.name))
      .map((entry) => {
        const contents = readFileSync(path.join(publicDir, entry.name))
        return {
          url: `/${entry.name}`,
          revision: createHash('md5').update(contents).digest('hex'),
        }
      })
  } catch {
    return []
  }
}

const nextConfig: NextConfig = {
  /**
   * The app's routes were renamed from Italian to English (`/canzonieri` →
   * `/songbooks`, and so on). These carry anyone with an old bookmark or a
   * shared link forward instead of a 404.
   */
  async redirects() {
    return [
      { source: '/canzonieri', destination: '/', permanent: true },
      { source: '/canzonieri/:slug', destination: '/songbooks/:slug', permanent: true },
      { source: '/canzoni/:slug', destination: '/songs/:slug', permanent: true },
      { source: '/canzoni/:slug/modifica', destination: '/songs/:slug/edit', permanent: true },
      { source: '/importa', destination: '/', permanent: true },
      /*
       * '/songbooks', '/import' and '/users' were pages of their own — create/rename/
       * remove a songbook, import songs into one, and manage collaborators — folded
       * into the home screen, into each songbook's own page, or removed outright
       * (collaborators, v3.1). Nothing replaces any of them directly, so all three
       * land on '/'; '/canzonieri', '/importa' and '/utenti' above go straight there
       * too, rather than bouncing through the routes they used to become before
       * those were retired.
       */
      { source: '/songbooks', destination: '/', permanent: true },
      { source: '/import', destination: '/', permanent: true },
      { source: '/users', destination: '/', permanent: true },
      { source: '/utenti', destination: '/', permanent: true },
    ]
  },
}

export default withSerwistInit({
  swSrc: 'src/app/sw.ts',
  swDest: 'public/sw.js',
  additionalPrecacheEntries: [...pageEntries(), ...publicEntries()],
  // Only ship a service worker from a real build; in dev it gets in the way.
  disable: process.env.NODE_ENV === 'development',
})(nextConfig)
