import { Analytics } from '@vercel/analytics/next'
import type { Metadata, Viewport } from 'next'
import { DM_Sans, Geist_Mono } from 'next/font/google'

import { OfflineSync } from '@/components/OfflineSync'
import { RoleProvider } from '@/components/RoleProvider'
import { APP_NAME, APP_PAYOFF } from '@/lib/brand'
import { STATUS_BAR_ID, THEME_KEY } from '@/lib/theme'

import './globals.css'

/*
 * DM Sans reads the app, Geist Mono reads the ChordPro.
 *
 * The variables are named for the job rather than the typeface, because the sheet
 * and the editor both depend on the app font being one thing: the editor positions
 * chords by measuring a hidden copy of the words, so the copy and the input have to
 * be set in the same family, and a name like `--font-sans` is the thing they share.
 */
const sans = DM_Sans({
  variable: '--font-sans',
  subsets: ['latin'],
})

const mono = Geist_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: { default: APP_NAME, template: `%s · ${APP_NAME}` },
  description: `${APP_PAYOFF}. Lyrics and chords for your repertoire, with transposition, notation and auto-scroll.`,
  applicationName: APP_NAME,
  /**
   * Declared rather than left to convention.
   *
   * `/favicon.ico` and `/apple-touch-icon.png` would be found by guesswork anyway,
   * but only the tags say which size is which — and iOS picks the touch icon from
   * the tag first. The files are generated by `npm run icons`; every one of them is
   * named `icon-*` or `apple-touch-icon` so the middleware serves it without a
   * session, which is what lets the install prompt show an icon on a locked app.
   */
  icons: {
    icon: [
      { url: '/icon-32.png', type: 'image/png', sizes: '32x32' },
      { url: '/icon-192.png', type: 'image/png', sizes: '192x192' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180' }],
  },
}

/**
 * Puts the reader's theme on the page before anything is painted.
 *
 * Inline and synchronous, as the first thing in the body: it cannot come from the
 * bundle, because by the time the bundle runs the page has already been painted in
 * the wrong theme and the reader has seen it flash. These pages are statically
 * generated and served from a precache, so there is no server render that could
 * know the answer either — this script is the only place it can be applied in time.
 *
 * Twin of `applyThemeChoice` in lib/theme.ts, which does the same on a change and
 * carries the explanation of why the attribute is removed rather than set to
 * "auto". The key and the id are imported so at least the strings cannot drift.
 */
const themeScript = `try{var c=localStorage.getItem('${THEME_KEY}');if(c==='light'||c==='dark'){var r=document.documentElement;r.dataset.theme=c;var b=getComputedStyle(r).getPropertyValue('--bg').trim();if(b){var m=document.createElement('meta');m.id='${STATUS_BAR_ID}';m.name='theme-color';m.content=b;document.head.prepend(m)}}}catch(e){}`

export const viewport: Viewport = {
  // No maximumScale or user-scalable: pinch zoom is an accessibility escape
  // hatch and the font stepper is not a substitute for it.
  width: 'device-width',
  initialScale: 1,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#f6f5f2' },
    { media: '(prefers-color-scheme: dark)', color: '#101216' },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sans.variable} ${mono.variable} antialiased`}>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />

        {/*
          * Here rather than in each page: one answer about who is looking, asked once and
          * kept across navigations. It gates what the screens offer, never what the server
          * allows — see RoleProvider.
          */}
        <RoleProvider>{children}</RoleProvider>
        {/*
          * Silent and stateless from the outside — see OfflineSync's own doc comment.
          * Mounted once here rather than per-page so a client-side navigation between
          * songs does not restart it.
          */}
        <OfflineSync />
        <Analytics />
      </body>
    </html>
  )
}
