import type { Metadata, Viewport } from 'next'
import { DM_Sans, Geist_Mono } from 'next/font/google'

import './globals.css'

/*
 * DM Sans reads the app, Geist Mono reads the ChordPro.
 *
 * The variables are named for the job rather than the typeface, because the sheet
 * and the editor both depend on the app font being one thing: the editor positions
 * chords by measuring a hidden copy of the words, so the copy and the input have to
 * be set in the same family, and a name like `--font-sans` is the thing they share.
 */
const sans = DM_Sans({
  variable: '--font-sans',
  subsets: ['latin'],
})

const mono = Geist_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: { default: 'songs', template: '%s · songs' },
  description: 'Testi e accordi, con trasposizione, notazione e scorrimento automatico.',
  applicationName: 'songs',
  /**
   * Declared rather than left to convention.
   *
   * `/favicon.ico` and `/apple-touch-icon.png` would be found by guesswork anyway,
   * but only the tags say which size is which — and iOS picks the touch icon from
   * the tag first. The files are generated by `npm run icons`; every one of them is
   * named `icon-*` or `apple-touch-icon` so the middleware serves it without a
   * session, which is what lets the install prompt show an icon on a locked app.
   */
  icons: {
    icon: [
      { url: '/icon-32.png', type: 'image/png', sizes: '32x32' },
      { url: '/icon-192.png', type: 'image/png', sizes: '192x192' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180' }],
  },
}

export const viewport: Viewport = {
  // No maximumScale or user-scalable: pinch zoom is an accessibility escape
  // hatch and the font stepper is not a substitute for it.
  width: 'device-width',
  initialScale: 1,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#f6f5f2' },
    { media: '(prefers-color-scheme: dark)', color: '#101216' },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="it">
      <body className={`${sans.variable} ${mono.variable} antialiased`}>{children}</body>
    </html>
  )
}
